---
title: "Results"
author: "Blain Morin"
date: "March 11, 2019"
output: pdf_document
---

```{r setup, include=FALSE}

library(dplyr)
library(stargazer)
library(metafor)


```

# Code for the functions:

```{r}
### Copas functions for Benefits
b.lik = function(theta, tau2) {
  
  QH = sum(log(pnorm((1.96*sH - theta)/sqrt(sH^2 + tau2)) - pnorm((-1.96*sH - theta)/sqrt(sH^2 + tau2))))
  
  -1 * sum((y - theta)^2/(s^2 + tau2) + log(s^2 + tau2))/2 + QH
  
}


b.CI = function(){
  
  lik1 = function(par, theta) { 
    -1 * b.lik(theta, par[1]) 
  }
  
  lik2 = function(theta, lik1){ 
    
    parhat = c(0)
    
    nlminb(parhat, lik1, lower = c(0), upper = c(Inf), theta = theta)$objective 
    
  }
  
  temp1 = nlminb(sum(y/s^2)/sum(1/s^2), lik2, lik1 = lik1)
  
  thetahat = temp1$par
  
  likmax = -1 * temp1$objective
  
  lik3 = function(theta, likmax, lik1, lik2){
    (likmax + lik2(theta, lik1) - 1.96)^2 
  }
  
  thetahatL = nlminb(thetahat - 0.01, lik3, upper = thetahat, likmax = likmax, lik1 = lik1, lik2 = lik2)$par
  
  thetahatU = nlminb(thetahat + 0.01, lik3, lower = thetahat, likmax = likmax, lik1 = lik1, lik2 = lik2)$par
  
  c(thetahatL, thetahat, thetahatU)
  
}

CIRE = function(){
  
  likRE = function(tau2, theta){ 
    sum((y - theta)^2/(s^2 + tau2) + log(s^2 + tau2))/2 
  }
  
  likRE1 = function(theta, likRE){
    nlminb(0, likRE, theta = theta, lower = 0)$objective 
  }
  
  temp = nlminb(sum(y/s^2)/sum(1/s^2), likRE1, likRE = likRE)
  
  thetaREhat = temp$par
  
  likREmax = -1 * temp$objective
  
  likRE2 = function(theta, likREmax, likRE, likRE1){ 
    (likREmax + likRE1(theta, likRE) - 1.96)^2 
  }
  
  thetaREhatL = nlminb(thetaREhat - 0.01, likRE2, upper = thetaREhat, likREmax = likREmax, likRE = likRE, likRE1 = likRE1)$par
  
  thetaREhatU = nlminb(thetaREhat + 0.01, likRE2, lower = thetaREhat, likREmax = likREmax, likRE = likRE, likRE1 = likRE1)$par
  
  c(thetaREhatL, thetaREhat, thetaREhatU)
  
}


```

```{r}

### HARM COPAS

h.lik = function(theta, tau2) {
  
  QH = sum(log(pnorm(theta/sqrt(sH^2 + tau2))))
  
  -1 * sum((y - theta)^2/(s^2 + tau2) + log(s^2 + tau2))/2 + QH
  
}


h.CI = function(){
  
  lik1 = function(par, theta) { 
    -1 * h.lik(theta, par[1]) 
  }
  
  lik2 = function(theta, lik1){ 
    
    parhat = c(0)
    
    nlminb(parhat, lik1, lower = c(0), theta = theta, upper = c(Inf))$objective
    
  }
  
  temp1 = nlminb(sum(y/s^2)/sum(1/s^2), lik2, lik1 = lik1)
  
  thetahat = temp1$par
  
  likmax = -1 * temp1$objective
  
  lik3 = function(theta, likmax, lik1, lik2){
    (likmax + lik2(theta, lik1) - 1.96)^2 
  }
  
  thetahatL = nlminb(thetahat - 0.01, lik3, upper = thetahat, likmax = likmax, lik1 = lik1, lik2 = lik2)$par
  
  thetahatU = nlminb(thetahat + 0.01, lik3, lower = thetahat, likmax = likmax, lik1 = lik1, lik2 = lik2)$par
  
  c(thetahatL, thetahat, thetahatU)
  
}

```


```{r total vte}

################## Total VTE #######################

########## Paper Reported Numbers #################

### LMWH
as = c(24, 3, 2, 17, 25, 63)
n1 = c(127, 74, 82, 248, 2195, 144)

### FXaI
cs = c(16, 2, 7, 6, 10, 32)
n2 = c(120, 72, 134, 255, 2199, 151)


### ni for each High risk of bias
nhigh = c()


### Calculate ORs and variances
ors = escalc(measure = "OR", ai = as, n1i = n1, ci = cs, n2i = n2)

y = ors$yi
s = sqrt(ors$vi)
nreported = n1 + n2


### Estimate unreported variances
kbar = sum(s^-2)/sum(nreported)

sH = sqrt(1/(kbar*nhigh))

unadjusted = exp(CIRE())
adjusted = exp(b.CI())
n.high = length(nhigh)


############## Include Blain Calcs #######################

### LMWH
as = c(24, 3, 2, 17, 25, 63, 48, 5, 66, 85, 24)
n1 = c(127, 74, 82, 248, 2195, 144, 314, 83, 797, 918, 351)

### FXaI
cs = c(16, 2, 7, 6, 10, 32, 36, 6, 48, 37, 26)
n2 = c(120, 72, 134, 255, 2199, 151, 247, 84, 787, 908, 350)


### ni for each High risk of bias
nhigh = c()


### Calculate ORs and variances
ors = escalc(measure = "OR", ai = as, n1i = n1, ci = cs, n2i = n2)

y = ors$yi
s = sqrt(ors$vi)
nreported = n1 + n2


### Estimate unreported variances
kbar = sum(s^-2)/sum(nreported)

sH = sqrt(1/(kbar*nhigh))

unadjusted2 = exp(CIRE())
adjusted2 = exp(b.CI())
n.high2 = length(nhigh)

Total.VTE = c(unadjusted, adjusted, unadjusted2, adjusted2, n.high2)

```

```{r symptomatic vte}

################## Symptomatic VTE #######################

########## Paper Reported Numbers #################

### LMWH
as = c(0, 48, 0, 13, 9)
n1 = c(127, 314, 83, 1128, 1123)

### FXaI
cs = c(1, 36, 1, 29, 12)
n2 = c(120, 274, 84, 1126, 1129)


### ni for each High risk of bias
nhigh = c(4394, 295)


### Calculate ORs and variances
ors = escalc(measure = "OR", ai = as, n1i = n1, ci = cs, n2i = n2)

y = ors$yi
s = sqrt(ors$vi)
nreported = n1 + n2


### Estimate unreported variances
kbar = sum(s^-2)/sum(nreported)

sH = sqrt(1/(kbar*nhigh))

unadjusted = exp(CIRE())
adjusted = exp(b.CI())
n.high = length(nhigh)


############## Include Blain Calcs #######################

### LMWH
as = c(0, 48, 0, 13, 9, 0, 8)
n1 = c(127, 314, 83, 1128, 1123, 82, 351)

### FXaI
cs = c(1, 36, 1, 29, 12, 1, 8)
n2 = c(120, 274, 84, 1126, 1129, 134, 350)


### ni for each High risk of bias
nhigh = c(4394, 295)


### Calculate ORs and variances
ors = escalc(measure = "OR", ai = as, n1i = n1, ci = cs, n2i = n2)

y = ors$yi
s = sqrt(ors$vi)
nreported = n1 + n2


### Estimate unreported variances
kbar = sum(s^-2)/sum(nreported)

sH = sqrt(1/(kbar*nhigh))

unadjusted2 = exp(CIRE())
adjusted2 = exp(b.CI())
n.high2 = length(nhigh)

Symptomatic.VTE = c(unadjusted, adjusted, unadjusted2, adjusted2, n.high2)

```

```{r total PE}

################## Total PE #######################

########## Paper Reported Numbers #################

### LMWH
as = c(5, 1 , 2)
n1 = c(2699, 1128, 1123)

### FXaI
cs = c(3, 5, 2)
n2 = c(2708, 1126, 1129)


### ni for each High risk of bias
nhigh = c(295, 588)


### Calculate ORs and variances
ors = escalc(measure = "OR", ai = as, n1i = n1, ci = cs, n2i = n2)

y = ors$yi
s = sqrt(ors$vi)
nreported = n1 + n2


### Estimate unreported variances
kbar = sum(s^-2)/sum(nreported)

sH = sqrt(1/(kbar*nhigh))

unadjusted = exp(CIRE())
adjusted = exp(b.CI())
n.high = length(nhigh)


############## Include Blain Calcs #######################

### LMWH
as = c(5, 1 , 2, 0, 1)
n1 = c(2699, 1128, 1123, 82, 351)

### FXaI
cs = c(3, 5, 2, 1, 2)
n2 = c(2708, 1126, 1129, 134, 350)


### ni for each High risk of bias
nhigh = c(295, 588)


### Calculate ORs and variances
ors = escalc(measure = "OR", ai = as, n1i = n1, ci = cs, n2i = n2)

y = ors$yi
s = sqrt(ors$vi)
nreported = n1 + n2


### Estimate unreported variances
kbar = sum(s^-2)/sum(nreported)

sH = sqrt(1/(kbar*nhigh))

unadjusted2 = exp(CIRE())
adjusted2 = exp(b.CI())
n.high2 = length(nhigh)

Total.PE = c(unadjusted, adjusted, unadjusted2, adjusted2, n.high2)

```

```{r total DVT}

################## Fatal PE #######################

########## Paper Reported Numbers #################

### LMWH
as = c(24, 3, 2, 17, 68, 5, 7, 65, 83, 23)
n1 = c(127, 74, 82, 248, 1911, 83, 53, 796, 918, 351)

### FXaI
cs = c(16, 2, 6, 6, 22, 6, 0, 44, 36, 24)
n2 = c(120, 72, 133, 255, 1944, 84, 53, 784, 908, 350)


### ni for each High risk of bias
nhigh = c(295, 588)


### Calculate ORs and variances
ors = escalc(measure = "OR", ai = as, n1i = n1, ci = cs, n2i = n2)

y = ors$yi
s = sqrt(ors$vi)
nreported = n1 + n2


### Estimate unreported variances
kbar = sum(s^-2)/sum(nreported)

sH = sqrt(1/(kbar*nhigh))

unadjusted = exp(CIRE())
adjusted = exp(b.CI())
n.high = length(nhigh)


############## Include Blain Calcs #######################

### LMWH
as = c(24, 3, 2, 17, 68, 5, 7, 65, 83, 23)
n1 = c(127, 74, 82, 248, 1911, 83, 53, 796, 918, 351)

### FXaI
cs = c(16, 2, 6, 6, 22, 6, 0, 44, 36, 24)
n2 = c(120, 72, 133, 255, 1944, 84, 53, 784, 908, 350)


### ni for each High risk of bias
nhigh = c(295, 588)

### Calculate ORs and variances
ors = escalc(measure = "OR", ai = as, n1i = n1, ci = cs, n2i = n2)

y = ors$yi
s = sqrt(ors$vi)
nreported = n1 + n2


### Estimate unreported variances
kbar = sum(s^-2)/sum(nreported)

sH = sqrt(1/(kbar*nhigh))

unadjusted2 = exp(CIRE())
adjusted2 = exp(b.CI())
n.high2 = length(nhigh)

Total.DVT = c(unadjusted, adjusted, unadjusted2, adjusted2, n.high2)

```

```{r syptomatic DVT}

################## Fatal PE #######################

########## Paper Reported Numbers #################

### LMWH
as = c(0, 5, 0, 0, 1, 7)
n1 = c(127, 2699, 83, 1128, 1123, 351)

### FXaI
cs = c(1, 1, 1, 5, 3, 6)
n2 = c(120, 2708, 84, 1126, 1129, 350)


### ni for each High risk of bias
nhigh = c(295, 588)


### Calculate ORs and variances
ors = escalc(measure = "OR", ai = as, n1i = n1, ci = cs, n2i = n2)

y = ors$yi
s = sqrt(ors$vi)
nreported = n1 + n2


### Estimate unreported variances
kbar = sum(s^-2)/sum(nreported)

sH = sqrt(1/(kbar*nhigh))

unadjusted = exp(CIRE())
adjusted = exp(b.CI())
n.high = length(nhigh)


############## Include Blain Calcs #######################

### LMWH
as = c(0, 5, 0, 0, 1, 7)
n1 = c(127, 2699, 83, 1128, 1123, 351)

### FXaI
cs = c(1, 1, 1, 5, 3, 6)
n2 = c(120, 2708, 84, 1126, 1129, 350)


### ni for each High risk of bias
nhigh = c(295, 588)

### Calculate ORs and variances
ors = escalc(measure = "OR", ai = as, n1i = n1, ci = cs, n2i = n2)

y = ors$yi
s = sqrt(ors$vi)
nreported = n1 + n2


### Estimate unreported variances
kbar = sum(s^-2)/sum(nreported)

sH = sqrt(1/(kbar*nhigh))

unadjusted2 = exp(CIRE())
adjusted2 = exp(b.CI())
n.high2 = length(nhigh)

Symptomatic.DVT = c(unadjusted, adjusted, unadjusted2, adjusted2, n.high2)

```

```{r proximal DVT}

################## Proximal DVT #######################

########## Paper Reported Numbers #################

### LMWH
as = c(5, 2, 20, 20, 0, 10, 23)
n1 = c(127, 248, 2190, 144, 83, 830, 927)

### FXaI
cs = c(2, 1, 7, 5, 1, 14, 6)
n2 = c(120, 255, 2196, 151, 84, 816, 922)


### ni for each High risk of bias
nhigh = c(588, 701)


### Calculate ORs and variances
ors = escalc(measure = "OR", ai = as, n1i = n1, ci = cs, n2i = n2)

y = ors$yi
s = sqrt(ors$vi)
nreported = n1 + n2


### Estimate unreported variances
kbar = sum(s^-2)/sum(nreported)

sH = sqrt(1/(kbar*nhigh))

unadjusted = exp(CIRE())
adjusted = exp(b.CI())
n.high = length(nhigh)


############## Include Blain Calcs #######################

### LMWH
as = c(5, 2, 20, 20, 0, 10, 23)
n1 = c(127, 248, 2190, 144, 83, 830, 927)

### FXaI
cs = c(2, 1, 7, 5, 1, 14, 6)
n2 = c(120, 255, 2196, 151, 84, 816, 922)


### ni for each High risk of bias
nhigh = c(588, 701)

### Calculate ORs and variances
ors = escalc(measure = "OR", ai = as, n1i = n1, ci = cs, n2i = n2)

y = ors$yi
s = sqrt(ors$vi)
nreported = n1 + n2


### Estimate unreported variances
kbar = sum(s^-2)/sum(nreported)

sH = sqrt(1/(kbar*nhigh))

unadjusted2 = exp(CIRE())
adjusted2 = exp(b.CI())
n.high2 = length(nhigh)

Proximal.DVT = c(unadjusted, adjusted, unadjusted2, adjusted2, n.high2)

```

```{r major bleeding}

################## Proximal DVT #######################

########## Paper Reported Numbers #################

### LMWH
as = c(1, 0, 6, 18, 0, 11, 32, 9)
n1 = c(166, 87, 301, 2659, 172, 1129, 1133, 351)

### FXaI
cs = c(1, 1, 2, 22, 1, 20,47, 10)
n2 = c(163, 85, 303, 2673, 170, 1128, 1140, 350)


### ni for each High risk of bias
nhigh = c()


### Calculate ORs and variances
ors = escalc(measure = "OR", ai = as, n1i = n1, ci = cs, n2i = n2)

y = ors$yi
s = sqrt(ors$vi)
nreported = n1 + n2


### Estimate unreported variances
kbar = sum(s^-2)/sum(nreported)

sH = sqrt(1/(kbar*nhigh))

unadjusted = exp(CIRE())
adjusted = exp(h.CI())
n.high = length(nhigh)


############## Include Blain Calcs #######################

### LMWH
as = c(1, 0, 6, 18, 0, 11, 32, 9, 8)
n1 = c(166, 87, 301, 2659, 172, 1129, 1133, 351, 314)

### FXaI
cs = c(1, 1, 2, 22, 1, 20,47, 10, 25)
n2 = c(163, 85, 303, 2673, 170, 1128, 1140, 350, 274)


### ni for each High risk of bias
nhigh = c()


### Calculate ORs and variances
ors = escalc(measure = "OR", ai = as, n1i = n1, ci = cs, n2i = n2)

y = ors$yi
s = sqrt(ors$vi)
nreported = n1 + n2


### Estimate unreported variances
kbar = sum(s^-2)/sum(nreported)

sH = sqrt(1/(kbar*nhigh))

unadjusted2 = exp(CIRE())
adjusted2 = exp(h.CI())
n.high2 = length(nhigh)

Major.Bleeding = c(unadjusted, adjusted, unadjusted2, adjusted2, n.high2)

```